spring:
  datasource:
    url: jdbc:mysql://localhost:3306/martech_sit_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1688

logging:
  path: ./logs
  config: classpath:logback.xml

